Harden input validation shell step
Move dockerfile and ubuntu_version inputs into environment variables
before executing the check. This avoids direct expression
interpolation in the run block and fixes the stray extra `fi` that
caused shell syntax errors.

Signed-off-by: Leandro Lucarella <luca-frequenz@llucax.com>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -70,11 +70,13 @@ runs:
 
     - name: Check inputs
       shell: bash
+      env:
+        DOCKERFILE: ${{ inputs.dockerfile }}
+        UBUNTU_VERSION: ${{ inputs.ubuntu_version }}
       run: |
-        if test -z "${{ inputs.dockerfile }}" -a -z "${{ inputs.ubuntu_version }}"; then \
-            echo "::error ::At least one of `dockerfile` or `ubuntu_version` should be set"; \
-            exit 1; \
-          fi; \
+        if test -z "$DOCKERFILE" -a -z "$UBUNTU_VERSION"; then
+          echo "::error ::At least one of 'dockerfile' or 'ubuntu_version' should be set"
+          exit 1
         fi
 
     - name: Set up QEMU
